<a href="https://colab.research.google.com/github/Filipsys/intermediate_python/blob/main/Tensorflow_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [89]:
# Import Tensorflow
import tensorflow as tf

print(tf.__version__)

2.11.0


In [90]:
# Create tensors with tf.constant()
scalar = tf.constant(7)

scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [91]:
# Check the number of dimensions of a tensor 
# (ndim stands for nuber of dimensions)
scalar.ndim

0

In [92]:
# Create a vector
vector = tf.constant([10, 10])

vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [93]:
# Check the dimension of our vector
vector.ndim

1

In [94]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7],
                     [7, 10]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [95]:
matrix.ndim

2

In [96]:
# Create another matrix

another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9,]], dtype = tf.float16)

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [97]:
another_matrix.ndim

2

In [98]:
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                       [[7, 8, 9],
                        [10, 11, 12]],
                       [[13, 14, 15],
                        [16, 17, 18]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [99]:
tensor.ndim

3

* Scalar: a single number
* Vector: a number with direction
* Matrix: a 2-dimensional array of numbers
* tensor: an n-dimensional array of numbers

In [100]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [101]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [102]:
changeable_tensor[0].assign(1)
changeable_tensor[1].assign(2)

changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>

In [103]:
# Random tensors
random_1 = tf.random.Generator.from_seed(12)
random_1 = random_1.normal(shape = (2, 3))

random_2 = tf.random.Generator.from_seed(43)
random_2 = random_2.normal(shape = (2, 3))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[-1.0130816 ,  0.2829171 ,  1.2132235 ],
        [ 0.46988973,  0.37944326, -0.6664026 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[-0.23193765, -1.8107855 ,  0.09988727],
        [-0.50998646, -0.7535806 , -0.5716629 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=bool, numpy=
 array([[False, False, False],
        [False, False, False]])>)

### Shuffle the order of elements in a tensor

In [104]:
not_shuffled = tf.constant([[10, 7, 9],
                           [2, 5, 6],
                           [4, 3, 4]])
 
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 4,  3,  4],
       [ 2,  5,  6],
       [10,  7,  9]], dtype=int32)>

In [105]:
tf.random.set_seed(42) # Global level seed
tf.random.shuffle(not_shuffled, seed = 42) # Operation level random seed

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10,  7,  9],
       [ 2,  5,  6],
       [ 4,  3,  4]], dtype=int32)>

In [106]:
tf.ones([6, 6])

<tf.Tensor: shape=(6, 6), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [107]:
tf.zeros(shape = (10, 10))

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [108]:
import numpy as np
numpy_A = np.arange(1, 25, dtype = np.int32) # Create a NumPy array from 1 and 25

numpy_A

# X = tf.constant(some_matrix) # capital for matrix
# y = tf.constant(vector) #non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [109]:
tensor_A = tf.constant(numpy_A, shape = (2, 3, 4))

tensor_A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

### Getting information on tensors

* Shape
* Rank
* Axis or dimension
* Size

In [110]:
# Create a rank 4 tensor

rank_4_tensor = tf.zeros(shape = [2, 3, 4, 5])

rank_4_tensor, rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
 array([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],
 
 
        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]], dtype=float32)>,
 TensorShape([2, 3, 4, 5]),
 4,
 <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [111]:
print(f"Datatype of every element: {rank_4_tensor.dtype}")
print(f"Number of dimensions (rank): {rank_4_tensor.ndim}")
print(f"Shape of tensor: {rank_4_tensor.shape}")
print(f"Elements along the 0 axis: {rank_4_tensor.shape[0]}")
print(f"Elements along the last axis: {rank_4_tensor.shape[-1]}")
print(f"Total number of elements in our tensor: {tf.size(rank_4_tensor).numpy()}")

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: 120


In [112]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [113]:
test_tensor1 = tf.zeros(shape = [1, 2, 10, 10])

test_tensor1, test_tensor1.ndim, tf.size(test_tensor1).numpy()

(<tf.Tensor: shape=(1, 2, 10, 10), dtype=float32, numpy=
 array([[[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
    

In [114]:
rank_4_tensor[:, :, :, :1]

<tf.Tensor: shape=(2, 3, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [115]:
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [116]:
# Create rank 2 tensors
rank_2_tensor = tf.zeros(shape = [2, 2])
rank_2_tensor2 = tf.constant([[1, 2],
                              [3, 4]])

rank_2_tensor.ndim, rank_2_tensor2.ndim

(2, 2)

In [117]:
rank_2_tensor[:, -1], rank_2_tensor2[:, -1]

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0., 0.], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>)

In [118]:
# Add an extra dimension
rank_3_tensor2 = rank_2_tensor2[..., tf.newaxis]

rank_3_tensor2, rank_2_tensor2.ndim, rank_3_tensor2.ndim

(<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[1],
         [2]],
 
        [[3],
         [4]]], dtype=int32)>, 2, 3)

In [119]:
tf.expand_dims(rank_2_tensor2, axis = -1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [120]:
tf.expand_dims(rank_2_tensor2, axis = 0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>

### Manipulating tensors (tensor operations)

**Basic operations**
`+`, `-`, `*`, `/`

In [121]:
tensor = tf.constant(([10, 7], 
                      [3, 4]))

tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [122]:
# Original tensor is unchanged

tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [123]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [124]:
tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [125]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [126]:
tf.multiply(tensor, 100) # Faster on gpu

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1000,  700],
       [ 300,  400]], dtype=int32)>

In [127]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

**Matrix multiplication**

One of the most common operations

In [128]:
matrix1 = tf.constant([[2, 4],
                       [4, 6]])
matrix2 = tf.constant([[3, 2],
                       [6, 6]])

tf.matmul(matrix1, matrix2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 28],
       [48, 44]], dtype=int32)>

In [129]:
matrix1 @ matrix2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 28],
       [48, 44]], dtype=int32)>

In [130]:
X = tf.constant([[2, 3],
                 [4, 5],
                 [5, 6]])
Y = tf.constant([[3, 4],
                 [5, 6],
                 [7, 8]])

reshaped_Y = tf.reshape(Y, shape = (2, 3))

reshaped_X = tf.reshape(X, shape = (2, 3))

tf.matmul(X, reshaped_Y), tf.matmul(X, reshaped_Y)


(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[24, 29, 34],
        [42, 51, 60],
        [51, 62, 73]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[24, 29, 34],
        [42, 51, 60],
        [51, 62, 73]], dtype=int32)>)

In [131]:
# Also doable with transpose

tf.transpose(X), tf.reshape(X, shape = (2, 3))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[2, 4, 5],
        [3, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[2, 3, 4],
        [5, 5, 6]], dtype=int32)>)

In [132]:
tf.matmul(tf.transpose(matrix1), matrix2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 28],
       [48, 44]], dtype=int32)>

**The dot product**

Matrix multiplication is also referred to as the dot product.

* `tf.matmul()`
* `tf.tensordot()`

In [133]:
tf.tensordot(tf.transpose(X), Y, axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[61, 72],
       [76, 90]], dtype=int32)>

In [134]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[18, 28, 38],
       [32, 50, 68],
       [39, 61, 83]], dtype=int32)>

In [135]:
tf.matmul(X, tf.reshape(Y, shape = (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[24, 29, 34],
       [42, 51, 60],
       [51, 62, 73]], dtype=int32)>

In [136]:
# Check the values of Y , reshape Y and transposed Y
print(f"Normal Y: \n{Y} \n")

print(f"Y reshaped to (2, 3): \n{tf.reshape(Y, (2, 3))}")

print(f"Y transposed: \n{tf.transpose(Y)}")

Normal Y: 
[[3 4]
 [5 6]
 [7 8]] 

Y reshaped to (2, 3): 
[[3 4 5]
 [6 7 8]]
Y transposed: 
[[3 5 7]
 [4 6 8]]


Generally, when performing matrix multiplication on two tensors and one axes doesn't line up you should usually use `tf.transpose()`

* `tf.matmul()`
* `tf.tensordot()`
* `@`

In [137]:
B = tf.constant([[1.2, 1.4],
                [3.5, 6.7]])
C = tf.constant([[1, 1],
                [3, 6]])

B.dtype, C.dtype

(tf.float32, tf.int32)

In [138]:
# Change to float16

B = tf.cast(B, dtype = tf.float16)
C = tf.cast(C, dtype = tf.int16)

B, C

(<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
 array([[1.2, 1.4],
        [3.5, 6.7]], dtype=float16)>,
 <tf.Tensor: shape=(2, 2), dtype=int16, numpy=
 array([[1, 1],
        [3, 6]], dtype=int16)>)

In [139]:
B = tf.cast(B, dtype = tf.float32)

B

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.2001953, 1.4003906],
       [3.5      , 6.6992188]], dtype=float32)>

### Aggregating tensors

Aggregating tensors is condensing them from multiple values down to a smaller amount of values.

* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor



In [140]:
# Get the absolute values

C = tf.constant([-7, -10])

C

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [141]:
tf.abs(C)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [142]:
tf.reduce_max(C)

<tf.Tensor: shape=(), dtype=int32, numpy=-7>

In [143]:
tf.reduce_min(C)

<tf.Tensor: shape=(), dtype=int32, numpy=-10>

In [144]:
tf.reduce_mean(C)

<tf.Tensor: shape=(), dtype=int32, numpy=-8>

In [145]:
tf.reduce_sum(C)

<tf.Tensor: shape=(), dtype=int32, numpy=-17>

In [146]:
D = tf.constant(np.random.randint(0, 100, size = 60))

D

<tf.Tensor: shape=(60,), dtype=int64, numpy=
array([73,  2,  6, 87, 67,  4, 13, 30, 45,  1, 12, 53, 55, 15, 27, 65, 31,
       73,  7, 88, 41,  8, 49, 32, 82, 97, 64, 51, 25, 97, 46, 78, 46, 44,
       35, 30, 36, 12, 61, 92, 20,  6, 65, 28, 93, 78, 10, 21, 24, 26,  4,
       77, 79, 58, 89, 31,  3, 10, 53, 95])>

In [147]:
tf.size(D), D.shape, D.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=60>, TensorShape([60]), 1)

In [148]:
tf.reduce_min(D), tf.reduce_max(D), tf.reduce_sum(D), tf.reduce_mean(D)

(<tf.Tensor: shape=(), dtype=int64, numpy=1>,
 <tf.Tensor: shape=(), dtype=int64, numpy=97>,
 <tf.Tensor: shape=(), dtype=int64, numpy=2650>,
 <tf.Tensor: shape=(), dtype=int64, numpy=44>)

In [149]:
HIGH = tf.constant(np.random.randint(0, 10000, size = 10000))

HIGH

<tf.Tensor: shape=(10000,), dtype=int64, numpy=array([7003, 9226, 2210, ...,  431, 9546, 2473])>

In [150]:
tf.reduce_min(HIGH), tf.reduce_max(HIGH), tf.reduce_sum(HIGH), tf.reduce_mean(HIGH)

(<tf.Tensor: shape=(), dtype=int64, numpy=1>,
 <tf.Tensor: shape=(), dtype=int64, numpy=9998>,
 <tf.Tensor: shape=(), dtype=int64, numpy=50038852>,
 <tf.Tensor: shape=(), dtype=int64, numpy=5003>)

In [151]:
# Finding the varuance of our tensor

import tensorflow_probability as tfp

tfp.stats.variance(HIGH)

<tf.Tensor: shape=(), dtype=int64, numpy=8372047>

In [152]:
# Find the standard deviation

tf.math.reduce_std(tf.cast(HIGH, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=2893.449>

In [153]:
tf.math.reduce_variance(tf.cast(HIGH, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=8372047.0>

### **Find the positional maximum and minumum**

In [154]:
# Create a new tensor for finding positional maximum and minimum

tf.random.set_seed(42)

F = tf.random.uniform(shape = [50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [155]:
tf.reduce_max(F), tf.argmax(F)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>,
 <tf.Tensor: shape=(), dtype=int64, numpy=42>)

In [156]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [157]:
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [158]:
tf.reduce_min(F), tf.argmin(F)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>,
 <tf.Tensor: shape=(), dtype=int64, numpy=16>)

In [159]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Sqeezing a tensor (removing all single dimensions)

In [160]:
G = tf.constant(tf.random.uniform(shape = [50]), shape = (1, 1, 1, 1, 50))

G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
           0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
           0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
           0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
           0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
           0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
           0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
      dtype=float32)>

In [161]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [162]:
G_squeezed = tf.squeeze(G)

G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
        0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
        0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
        0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
        0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
        0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
        0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
        0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
        0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
        0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
       dtype=float32)>, TensorShape([50]))

One-hot encoding tensors

In [163]:
# Create a list of indices

some_list = [0, 1, 2, 3]

# One hot encode our list

tf.one_hot(some_list, depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [164]:
tf.one_hot(some_list, depth = 4, on_value = "yes", off_value = "no")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yes', b'no', b'no', b'no'],
       [b'no', b'yes', b'no', b'no'],
       [b'no', b'no', b'yes', b'no'],
       [b'no', b'no', b'no', b'yes']], dtype=object)>

### Squaring, log, square root

In [165]:
H = tf.range(1, 10)

In [166]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [167]:
tf.sqrt(tf.cast(H, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [168]:
tf.math.log(tf.cast(H, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and NumPy

In [169]:
J = tf.constant(np.array([3., 7., 10.]))

J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [170]:
# Convert the tensor back to a NumPy array

np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [171]:
# Convert tensor J to a NumPy array

J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [172]:
J = tf.constant([3.])

J.numpy()[0]

3.0

In [173]:
# The default types of each are slightly different

numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])

numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

In [174]:
tf.cast(numpy_J, tf.float32).dtype

tf.float32

### Finding access to GPUs

In [175]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [176]:
!nvidia-smi

Tue Feb 21 15:41:42 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   55C    P0    29W /  70W |    328MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

> **Note:** If you have access to a CUDA-enabled GPU, TensorFlow will automatically use it whenever possible.

### Execise material

1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
2. Find the shape, rank and size of the tensors you created in 1.
3. Create two tensors containing random values between 0 and 1 with shape [5, 300].
4. Multiply the two tensors you created in 3 using matrix multiplication.
5. Multiply the two tensors you created in 3 using dot product.
6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
7. Find the min and max values of the tensor you created in 6 along the first axis.
8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
10. One-hot encode the tensor you created in 9.

In [178]:
mat_tensor = tf.constant(np.array([[3., 4., 5.],
                                   [6., 7., 8.],
                                   [9., 10., 11.]]))

mat_tensor

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])>

In [181]:
mat_tensor.shape, mat_tensor.dtype, tf.size(mat_tensor)

(TensorShape([3, 3]), tf.float64, <tf.Tensor: shape=(), dtype=int32, numpy=9>)

In [188]:
mat_tensor_1 = tf.constant(tf.random.uniform(shape = (5, 300), minval = 0, maxval = 2, dtype = tf.int32))
mat_tensor_2 = tf.constant(tf.random.uniform(shape = (5, 300), minval = 0, maxval = 2, dtype = tf.int32))

mat_tensor_1, mat_tensor_2

(<tf.Tensor: shape=(5, 300), dtype=int32, numpy=
 array([[0, 1, 0, ..., 0, 1, 1],
        [1, 1, 1, ..., 1, 1, 0],
        [1, 0, 1, ..., 1, 0, 1],
        [1, 1, 0, ..., 1, 0, 1],
        [1, 1, 1, ..., 1, 1, 0]], dtype=int32)>,
 <tf.Tensor: shape=(5, 300), dtype=int32, numpy=
 array([[1, 1, 1, ..., 0, 1, 1],
        [0, 1, 0, ..., 1, 1, 0],
        [0, 1, 0, ..., 1, 0, 1],
        [0, 1, 1, ..., 1, 1, 0],
        [0, 0, 0, ..., 0, 1, 1]], dtype=int32)>)

In [196]:
tf.matmul(mat_tensor_1, mat_tensor_2, transpose_a = True), tf.matmul(tf.transpose(mat_tensor_1), mat_tensor_2)

(<tf.Tensor: shape=(300, 300), dtype=int32, numpy=
 array([[0, 3, 1, ..., 3, 3, 2],
        [1, 3, 2, ..., 2, 4, 2],
        [0, 2, 0, ..., 2, 2, 2],
        ...,
        [0, 3, 1, ..., 3, 3, 2],
        [1, 2, 1, ..., 1, 3, 2],
        [1, 3, 2, ..., 2, 2, 2]], dtype=int32)>,
 <tf.Tensor: shape=(300, 300), dtype=int32, numpy=
 array([[0, 3, 1, ..., 3, 3, 2],
        [1, 3, 2, ..., 2, 4, 2],
        [0, 2, 0, ..., 2, 2, 2],
        ...,
        [0, 3, 1, ..., 3, 3, 2],
        [1, 2, 1, ..., 1, 3, 2],
        [1, 3, 2, ..., 2, 2, 2]], dtype=int32)>)

In [198]:
tf.matmul(mat_tensor_1, mat_tensor_2, transpose_b = True)

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[81, 68, 79, 69, 73],
       [85, 71, 93, 74, 81],
       [69, 56, 71, 64, 66],
       [80, 69, 77, 74, 70],
       [92, 80, 82, 93, 74]], dtype=int32)>

In [204]:
tf.tensordot(tf.cast(mat_tensor_1, dtype = tf.float32), tf.transpose(tf.cast(mat_tensor_2, dtype = tf.float32)), axes = 1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[81., 68., 79., 69., 73.],
       [85., 71., 93., 74., 81.],
       [69., 56., 71., 64., 66.],
       [80., 69., 77., 74., 70.],
       [92., 80., 82., 93., 74.]], dtype=float32)>

In [206]:
mat_tensor_3 = tf.constant(tf.random.uniform(shape = (224, 224, 3), minval = 0, maxval = 2, dtype = tf.int32))

mat_tensor_3

<tf.Tensor: shape=(224, 224, 3), dtype=int32, numpy=
array([[[1, 1, 0],
        [0, 0, 1],
        [1, 0, 0],
        ...,
        [0, 0, 1],
        [0, 1, 1],
        [1, 0, 0]],

       [[0, 1, 1],
        [1, 0, 1],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [1, 0, 1],
        [0, 0, 1]],

       [[1, 1, 1],
        [0, 1, 0],
        [0, 1, 0],
        ...,
        [1, 1, 0],
        [0, 0, 0],
        [1, 1, 1]],

       ...,

       [[0, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        ...,
        [1, 1, 0],
        [0, 0, 0],
        [0, 1, 1]],

       [[0, 0, 1],
        [0, 1, 0],
        [1, 1, 1],
        ...,
        [1, 0, 1],
        [0, 1, 0],
        [1, 0, 1]],

       [[1, 0, 0],
        [1, 1, 1],
        [0, 1, 1],
        ...,
        [1, 1, 1],
        [1, 0, 1],
        [0, 1, 1]]], dtype=int32)>

In [209]:
tf.reduce_min(mat_tensor_3[0])

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [213]:
mat_tensor_4 = tf.constant(tf.random.uniform(shape = (1, 224, 224, 3), minval = 0, maxval = 2))

mat_tensor_4

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[1.1959734 , 0.42053056, 1.6823161 ],
         [1.3154452 , 0.5702772 , 0.19695187],
         [1.8069124 , 0.4752984 , 0.5954211 ],
         ...,
         [0.80249286, 1.6490679 , 0.9908538 ],
         [0.35236764, 1.1324704 , 0.98555636],
         [1.4930496 , 1.2101617 , 0.09107161]],

        [[1.6383679 , 0.07921195, 0.8361442 ],
         [0.46177483, 1.4631374 , 1.3852768 ],
         [1.1483061 , 1.5312567 , 0.63012385],
         ...,
         [1.8218391 , 0.81717014, 1.8395355 ],
         [1.0114748 , 0.6755059 , 0.6530788 ],
         [1.4599974 , 1.887315  , 0.26868343]],

        [[0.93977547, 0.9623852 , 1.8743339 ],
         [1.4093311 , 0.6365583 , 0.1188271 ],
         [0.404593  , 1.8818936 , 0.36445832],
         ...,
         [1.399965  , 0.99185085, 0.24063182],
         [1.6783669 , 1.5755951 , 0.8950975 ],
         [1.1186624 , 1.3323536 , 1.2886217 ]],

        ...,

        [[0.5073366 , 0.2222352 , 

In [214]:
tf.squeeze(mat_tensor_4)

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[1.1959734 , 0.42053056, 1.6823161 ],
        [1.3154452 , 0.5702772 , 0.19695187],
        [1.8069124 , 0.4752984 , 0.5954211 ],
        ...,
        [0.80249286, 1.6490679 , 0.9908538 ],
        [0.35236764, 1.1324704 , 0.98555636],
        [1.4930496 , 1.2101617 , 0.09107161]],

       [[1.6383679 , 0.07921195, 0.8361442 ],
        [0.46177483, 1.4631374 , 1.3852768 ],
        [1.1483061 , 1.5312567 , 0.63012385],
        ...,
        [1.8218391 , 0.81717014, 1.8395355 ],
        [1.0114748 , 0.6755059 , 0.6530788 ],
        [1.4599974 , 1.887315  , 0.26868343]],

       [[0.93977547, 0.9623852 , 1.8743339 ],
        [1.4093311 , 0.6365583 , 0.1188271 ],
        [0.404593  , 1.8818936 , 0.36445832],
        ...,
        [1.399965  , 0.99185085, 0.24063182],
        [1.6783669 , 1.5755951 , 0.8950975 ],
        [1.1186624 , 1.3323536 , 1.2886217 ]],

       ...,

       [[0.5073366 , 0.2222352 , 0.48911142],
        [1.35

In [235]:
mat_tensor_5 = tf.constant(tf.random.uniform(shape = [10], minval = 0, maxval = 10, dtype = tf.int32))
mat_tensor_5_1 = tf.constant(tf.random.uniform(shape = (10,), minval = 0, maxval = 1000, dtype = tf.int32))

mat_tensor_5, mat_tensor_5_1, mat_tensor_5.shape == mat_tensor_5_1.shape

(<tf.Tensor: shape=(10,), dtype=int32, numpy=array([6, 8, 4, 1, 9, 1, 4, 6, 6, 7], dtype=int32)>,
 <tf.Tensor: shape=(10,), dtype=int32, numpy=array([615, 103, 368, 809, 896, 921, 909, 824, 933, 630], dtype=int32)>,
 True)

In [236]:
tf.one_hot(mat_tensor_5.numpy(), depth = 10), mat_tensor_5, mat_tensor_5.numpy()

(<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
 array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(10,), dtype=int32, numpy=array([6, 8, 4, 1, 9, 1, 4, 6, 6, 7], dtype=int32)>,
 array([6, 8, 4, 1, 9, 1, 4, 6, 6, 7], dtype=int32))

In [238]:
mat_tensor_6 = tf.constant([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

tf.one_hot(mat_tensor_6, depth = 10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>

In [239]:
tf.reduce_max(mat_tensor_6)

<tf.Tensor: shape=(), dtype=int32, numpy=9>